version: "3.8"
services:
  postgres:
    image: postgres:16.2-bookworm
    container_name: postgres-db
    ports:
      - '5432:5432'
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-}
      - POSTGRES_USER=${POSTGRES_USER:-}
      - POSTGRES_DB=${POSTGRES_DB:-}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./runtime/postgresql/init:/docker-entrypoint-initdb.d
      - ./runtime/postgresql/data:/tmp/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - open_powerlifting_network
    profiles:
      - base
    entrypoint: ["sh", "-c", "chown -R postgres:postgres /tmp/data/ && exec docker-entrypoint.sh postgres"]
volumes:
  pgdata:
    name: vol-postgres-db
networks:
  open_powerlifting_network:
    name: open_powerlifting_network
    external: true

  